FROM caddy:2-alpine

# Copy pre-built frontend
COPY dist /usr/share/caddy

# Copy Caddyfile
COPY ../Caddyfile /etc/caddy/Caddyfile

EXPOSE 80 443

CMD ["caddy", "run", "--config", "/etc/caddy/Caddyfile", "--adapter", "caddyfile"]